import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  header: {
    height: 200,
    borderWidth: 1,
    width: '100%',
  },
  profile: {
    height: 200,
    width: '100%',
    marginTop: 25,
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'center',
  },
  imgProfile: {
    height: 100,
    width: 100,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: 'white',
  },
  infoWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  colName: {
    fontFamily: 'NotoSansMono',
    fontSize: 20,
    color: '#3d465f',
    fontWeight: 'bold',
    marginBottom: 10,
    alignSelf: 'center',
  },
  barContainer: {
    width: '90%',
    paddingVertical: 5,
    flexDirection: 'column',
    marginTop: 25,
    backgroundColor: 'white',
    borderRadius: 20,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    paddingHorizontal: 20,
  },
  itemDesc: {
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  floorDesc: {
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  totalFloorDesc: {
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  oneDayDesc: {
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  oneDayChange: {
    flexDirection: 'row',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsWrap: {
    width: '100%',
    marginTop: 40,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  statsHead: {
    height: 100,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 30,
    alignContent: 'center',
  },
  statsHeadPercent: {
    width: 100,
    height: 100,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  stats: {
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  percentTitle: {
    fontFamily: 'NotoSansMono',
    fontSize: 20,
    color: '#3d465f',
    fontWeight: 'bold',
  },
  percentSecondary: {
    fontFamily: 'NotoSansMono',
    fontSize: 18,
    color: '#82FFA3',
    alignSelf: 'flex-start',
  },
  barItemInfo: {
    fontFamily: 'NotoSansMono',
    fontSize: 16,
    color: '#3d465f',
    marginLeft: 3,
    fontWeight: 'bold',
  },
  option1: {
    fontFamily: 'NotoSansMono',
    fontSize: 14,
    color: '#3d465f',
  },
  option2: {
    fontFamily: 'NotoSansMono',
    fontSize: 14,
    color: '#3d465f',
  },
  option3: {
    fontFamily: 'NotoSansMono',
    fontSize: 14,
    color: '#3d465f',
  },
  option1wrap: {
    height: 40,
    width: 60,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: 10,
    borderTopLeftRadius: 10,
  },
  option2wrap: {
    height: 40,
    width: 60,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  option3wrap: {
    height: 40,
    width: 60,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  statsHeadOption: {
    flexDirection: 'row',
    borderRadius: 10,
    alignItems: 'center',
    alignContent: 'center',
    padding: 5,
    backgroundColor: '#EEEEEE',
  },
  recentWrap: {
    flexDirection: 'row',
    width: '100%',
    marginTop: 10,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  recentText: {
    fontFamily: 'NotoSansMono',
    fontSize: 20,
    color: '#3d465f',
    fontWeight: 'bold',
  },
  recentArrow: {
    fontFamily: 'NotoSansMono',
    fontSize: 20,
    color: '#3d465f',
    fontWeight: 'bold',
  },
});
export default styles;
