import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  cardList: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    width: 200,
    height: 200,
    marginTop: 10,
    borderRadius: 10,
    marginRight: 30,
  },
  cardDescWrap: {
    flexDirection: 'column',
    justifyContent: 'flex-end',
    height: 120,
    padding: 20,
  },
  cardNameWrap: {
    width: 150,
    height: 60,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardNameText: {
    fontFamily: 'NotoSansMono',
    fontSize: 20,
    color: '#3d465f',
    fontWeight: 'bold',
  },
  cardNameTextSecondary: {
    fontFamily: 'NotoSansMono',
    fontSize: 12,
    color: '#3d465f',
  },
  cardColWralp: {
    flexDirection: 'column',
    width: '80%',
    alignSelf: 'center',
    height: 300,
    marginTop: 10,
    marginBottom: 10,
  },
  cardColTitleWrap: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'flex-end',
    borderWidth: 2,
    borderColor: 'white',
    margin: 10,
    borderRadius: 10,
    padding: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardColTitle: {},
  cardColWrap: {
    flexDirection: 'column',
    width: 200,
    alignSelf: 'center',
    justifyContent: 'flex-end',
    height: 200,
    marginRight: 10,
  },
  cardColTitleWrapToken: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'flex-end',
    borderWidth: 2,
    borderColor: 'white',
    margin: 10,
    borderRadius: 10,
    padding: 10,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
export default styles;
